spring:
  profiles:
    active: ${PROFILE:dev}
  jpa:
#    open-in-view: false
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
      path: /h2-console
